component_depth: 1
languages:
- cpp

exclude:
- /data/.*
- /package/.*
- /vagrant/.*
- /src/.*
- /FreeCAD/src/.*
- /subuser/freecad-dev/.*
- /src/3rdParty/.*
- /src/App/.*
- /src/Build/.*
- /src/Doc/.*
- /src/Ext/.*
- /src/Mod/.*
- /src/Base/.*
- /src/CXX/.*
- /src/MacAppBundle/*.
- /src/Gui/*.
- /src/Tools/*.
- /src/WindowsInstaller/.*
- /src/zipios++/.*
